app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('login', [
  'as'   => 'login',
  'uses' => 'UserController@getLogin'
]);

Route::post('login', [
  'as'   => 'login',
  'uses' => 'UserController@postLogin'
]);

Route::get('logout', [
  'as'   => 'logout',
  'uses' => 'UserController@getLogout'
]);

Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function(){
    Route::group(['middleware' => 'plebs'], function(){
      Route::resource('pengiriman', 'PengirimanController');
    });

    Route::group(['middleware' => 'superuser'], function(){
      Route::resource('kantordistribusi', 'KantorDistribusiController');
      Route::resource('kota', 'KotaController');
      Route::resource('user', 'UserController', [
        'except' => ['show']
      ]);
    });

    //getIndex and getAllDaftarPengiriman can be done in more laravelistic using nested resource controller
    Route::controller('/', 'DashboardController', [
      'getIndex'               => 'admin.index',
      'getAllDaftarPengiriman' => 'admin.all-pengiriman',
      'getDaftarPengiriman'    => 'admin.status-pengiriman',
      'getPaketMasuk'          => 'admin.getpaketmasuk',
      'postPaketMasuk'         => 'admin.postpaketmasuk',
      'getPaketKeluar'         => 'admin.getpaketkeluar',
      'postPaketKeluar'        => 'admin.postpaketkeluar',
    ]);
});

Route::controller('/', 'FrontendController', [
  'getIndex'      => 'home',
  'getAboutUs'    => 'aboutus',
  'getKantor'     => 'kantor',
  'getTracking'   => 'tracking',
  'postTracking'  => 'tracking',
  'getKonfirmasi' => 'konfirmasi',
  'postKonfirmasi'=> 'konfirmasi',
]);

resources/views/backends/dashboard.blade.php
@extends('templates.backend-base')
@section('css')
 @parent

@endsection
@section('js')
 @parent

@endsection
@section('title')
  Dashboard
@endsection
@section('subtitle')
  Order Status
@endsection
@section('page')
@foreach($statuspengiriman as $status)
<div class="col-lg-3 col-xs-6">
  <div class="small-box {{ $status->boxclass }}">
    <div class="inner">
      <h3>{{ count($status->pengiriman) }}</h3>
      <p>{{ $status->status }}</p>
    </div>
    <div class="icon">
      <i class="ion ion-cube"></i>
    </div>
    <a href="{{ route('admin.status-pengiriman', $status->id) }}" class="small-box-footer">Rincian <i class="fa fa-arrow-circle-right"></i></a>
  </div>
</div>
@endforeach
@endsection

resources/views/backends/kantor-form.blade.php
@extends('templates.backend-base')
@section('css')
  @parent
  <link rel="stylesheet" href="{{ asset('assets/css/form.css') }}">
@endsection
@section('js')
  @parent
  <script src="{{ asset('vendor/jquery-validation/dist/jquery.validate.min.js') }}"></script>
  <script src="{{ asset('vendor/twitter-bootstrap-wizard/jquery.bootstrap.wizard.min.js') }}"></script>
  <?php
  $latRef  = $kota->first()->lat;
  $longRef = $kota->first()->long;
  if((Input::old('lat') != "") && (Input::old('long') != ""))
  {
    $latRef = Input::old('lat');
    $longRef= Input::old('long');
  }
  elseif(Input::has('lat') && Input::has('long'))
  {
    $latRef = Input::get('lat');
    $longRef= Input::get('long');
  }
  ?>
  @include('gmapjs.base', ['lat' => $latRef, 'lng' => $longRef])
  <script src="{{ asset('assets/js/order.js') }}"></script>
  @include('gmapjs.probe-marker', ['parameter' => '#sKota_id', 'outLat' => '#sLat', 'outLong' => '#sLong'])
@endsection
@section('title')
Tambah Kantor / Edit Kantor
@endsection
@section('page')
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Rincian User</h3>
  </div>
  <form id="orderForm" role="form" method="post" action="@if(!Input::has('nama')){{ route('admin.kantordistribusi.store') }}@else{{ route('admin.kantordistribusi.update', $kantor->id) }}@endif">
    {!! csrf_field() !!}
    @if(Input::has('nama'))
    {!! method_field('PUT') !!}
    @endif
    <div class="box-body">
      <div id="rootwizard">
        <ul>
          <li><a href="#tab1" data-toggle="tab">Rincian</a></li>
          <li><a href="#tab2" data-toggle="tab">Posisi</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane" id="tab1">
            <h4 class="form-title">Data Dasar</h4>
            <hr>
            @include('templates.validation-base', ['parameter' => 'nama'])
            <div class="form-group">
              <label for="sNama">Nama</label>
              <input type="text" name="nama" id="sNama" value="@include('templates.value-input-template', ['parameter' => 'nama'])" class="form-control required">
            </div>
            @include('templates.validation-base', ['parameter' => 'alamat'])
            <div class="form-group">
              <label for="sAlamat">Alamat</label>
              <input type="text" name="alamat" id="sAlamat" value="@include('templates.value-input-template', ['parameter' => 'alamat'])" class="form-control required">
            </div>
            @include('templates.validation-base', ['paramater' => 'telepon'])
            <div class="form-group">
              <label for="sTelepon">Telepon</label>
              <input type="text" name="telepon" id="sTelepon" value="@include('templates.value-input-template', ['parameter' => 'telepon'])" class="form-control required">
            </div>
            @include('templates.validation-base', ['parameter' => 'kota_id'])
            <div class="form-group">
              <label for="sKota_id">Kota</label>
              <select class="form-control required" name="kota_id" id="sKota_id">
                @foreach($kota as $k)
                <option value="{{ $k->id }}" @include('templates.value-option-template', ['parameter' => 'kota_id', 'currId' => $k->id]) lat="{{ $k->lat }}" long="{{ $k->long }}">{{ $k->nama }}</option>
                @endforeach
              </select>
            </div>
          </div>
          <div class="tab-pane" id="tab2">
            <h4 class="form-title">Posisi Kantor</h4>
            <hr>
            <div class="row">
              <div class="col-md-8">
                <div class="" id="map-canvas"></div>
              </div>
              <div class="col-md-4">
                @include('templates.validation-base', ['parameter' => 'lat'])
                <div class="form-group">
                  <label for="sLat">Latitude</label>
                  <input type="text" name="lat" id="sLat" value="@include('templates.value-input-template', ['parameter' => 'lat'])" class="form-control required" readonly="true">
                </div>
                @include('templates.validation-base', ['parameter' => 'long'])
                <div class="form-group">
                  <label for="sLong">Longitude</label>
                  <input type="text" name="long" id="sLong" value="@include('templates.value-input-template', ['parameter' => 'long'])" class="form-control required" readonly="true">
                </div>
              </div>
            </div>
          </div>
          <hr>
          <div class="pull-right">
            <a class="btn btn-default" id="btn-next" href="#">Lanjut</a>
            <input type="submit" value="Simpan" class="btn btn-primary" id="btn-finish" style="display: none;" type="button">
          </div>
        </div>
      </div>
    </div>
  </form>
</div>
@endsection

resources/views/backends/kantor-list.blade.php
@extends('templates.backend-base')
@section('css')
  @parent
@endsection
@section('js')
  @parent
  <script src="{{ asset('assets/js/popup.js') }}"></script>
@endsection
@section('title')
Daftar Kantor Distribusi
@endsection
@section('page')
<div class="col-xs-12">
  <div class="box box-primary">
    <div class="box-header">
      <h3 class="box-title">List</h3>
      <div class="box-tools">
        <div class="input-group input-group-sm" style="width: 150px;">
          <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">
          <div class="input-group-btn">
            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        @include('templates.alert-base')
      </div>
    </div>
    <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
        <tr>
          <th>No</th>
          <th>Nama</th>
          <th>Alamat</th>
          <th>Kota</th>
          <th>Lat</th>
          <th>Long</th>
          <th></th>
          <th></th>
        </tr>
        <?php $point = 0 + ($kantor->currentPage() - 1) * $kantor->perPage(); ?>
        @foreach($kantor as $k)
        <tr>
          <td>{{ ++$point }}</td>
          <td><a href="#" onClick="PopupCenter('{{ route('admin.kantordistribusi.show', $k->id) }}', '123', '450', '620');">{{ $k->nama }}</a></td>
          <td>{{ $k->alamat }}</td>
          <td>{{ $k->kota->nama }}</td>
          <td>{{ $k->lat }}</td>
          <td>{{ $k->long }}</td>
          <td class="align-center">@if($k->kota != null)<a href="{{ route('admin.kantordistribusi.edit', $k->id) }}"><button class="btn btn-warning"><i class="ion ion-edit"></i></button></a>@endif</td>
          <td class="align-center">@if($k->kota != null)<form method="post" action="{{ route('admin.kantordistribusi.destroy', $k->id) }}">{!! method_field('delete') !!}{!! csrf_field() !!}<button type="submit" class="btn btn-danger"><i class="ion ion-close-circled"></i></button></form>@endif</td>
        </tr>
        @endforeach
      </table>
    </div>
  </div>
  <div class="text-center">
    {!! $kantor->render() !!}
  </div>
</div>
@endsection

resources/views/backends/kota-list.blade.php
@extends('templates.backend-base')
@section('css')
  @parent
@endsection
@section('js')
  @parent
  <script src="{{ asset('assets/js/popup.js') }}"></script>
@endsection
@section('title')
Daftar Kota
@endsection
@section('page')
<div class="col-xs-12">
  <div class="box box-primary">
    <div class="box-header">
      <h3 class="box-title">Kota</h3>
      <div class="box-tools">
        <div class="input-group input-group-sm" style="width: 150px;">
          <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">
          <div class="input-group-btn">
            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        @include('templates.alert-base')
      </div>
    </div>
    <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
        <tr>
          <th>No</th>
          <th>Nama</th>
          <th>Lat</th>
          <th>Long</th>
          <th></th>
          <th></th>
        </tr>
        <?php $point = 0 + ($kota->currentPage() - 1) * $kota->perPage() ; ?>
        @foreach($kota as $k)
        <tr>
          <td>{{ ++$point }}</td>
          <td><a href="#" onClick="PopupCenter('{{ route('admin.kota.show', $k->id) }}', '123', '450', '620');">{{ $k->nama }}</a></td>
          <td>{{ $k->lat }}</td>
          <td>{{ $k->long }}</td>
          <td class="align-center"><a href="{{ route('admin.kota.edit', $k->id) }}"><button class="btn btn-warning"><i class="ion ion-edit"></i></button></a></td>
          <td class="align-center"><form method="post" action="{{ route('admin.kota.destroy', $k->id) }}">{!! method_field('delete') !!}{!! csrf_field() !!}<button type="submit" class="btn btn-danger"><i class="ion ion-close-circled"></i></button></form></td>
        </tr>
        @endforeach
      </table>
    </div>
  </div>
  <div class="text-center">
    {!! $kota->render() !!}
  </div>
</div>
@endsection

resources/views/backends/pengiriman-form-status-only.blade.php
@extends('templates.backend-base')
@section('css')
  @parent
  <link rel="stylesheet" href="{{ asset('assets/css/form.css') }}">
@endsection
@section('js')
  @parent
  <script src="{{ asset('vendor/jquery-validation/dist/jquery.validate.min.js') }}"></script>
  <script src="{{ asset('vendor/twitter-bootstrap-wizard/jquery.bootstrap.wizard.min.js') }}"></script>
  <script src="{{ asset('assets/js/order.js') }}"></script>
  <script src="{{ asset('assets/js/popup.js') }}"></script>
@endsection
@section('title')
Edit Paket
@endsection
@section('page')
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Status Paket</h3>
  </div>
  <form id="orderForm" role="form" method="post" action="{{ route('admin.pengiriman.update', $pengiriman->id) }}">
    {!! csrf_field() !!}
    {!! method_field('PUT') !!}
    <div class="box-body">
      <div id="rootwizard">
        <ul>
          <li><a href="#tab1" data-toggle="tab">Pengiriman</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane" id="tab1">
            <h4 class="form-title">Status</h4>
            <small><a href="#" onClick="PopupCenter('{{ route('admin.pengiriman.show', $pengiriman->token) }}', '123', '450', '620');">{{ $pengiriman->token }}</a></small>
            <hr>
            @include('templates.validation-base', ['parameter' => 'statuspengiriman_id'])
            <div class="form-group">
              <label for="sStatus_Pengiriman">Status</label>
              <select class="form-control required" id="sStatus_Pengiriman" name="statuspengiriman_id">
                @foreach($statuspengiriman as $s)
                <option value="{{ $s->id }}" @include('templates.value-option-template', ['parameter' => 'statuspengiriman_id', 'currId' => $s->id])>{{ $s->status }}</option>
                @endforeach
              </select>
            </div>
            <p><b>Perhatian</b>: mengubah status pengiriman selain <span class="label label-warning">tertunda</span> akan mengakibatkan pengiriman tidak dapat diubah pada kantor yang sama untuk keduakalinya.</p>
            <p>
                Untuk status <span class="label label-primary">Perjalanan</span> pengubahan status berikutnya terjadi pada kantor berikutnya melalui menu <b>Mobilitas Paket</b>.<br/>
                Sedangkan status <span class="label label-success">Terkirim</span> dan <span class="label label-danger">Gagal</span> tidak dapat diubah apapun yang terjadi.
            </p>
          </div>
          <hr>
          <div class="pull-right">
            <a class="btn btn-default" id="btn-next" href="#">Lanjut</a>
            <input type="submit" value="Simpan" class="btn btn-primary" id="btn-finish" style="display: none;" type="button">
          </div>
        </div>
      </div>
    </div>
  </form>
</div>
@endsection

resources/views/backends/pengiriman-form.blade.php
@extends('templates.backend-base')
@section('css')
  @parent
  <link rel="stylesheet" href="{{ asset('assets/css/form.css') }}">
@endsection
@section('js')
  @parent
  <script src="{{ asset('vendor/jquery-validation/dist/jquery.validate.min.js') }}"></script>
  <script src="{{ asset('vendor/twitter-bootstrap-wizard/jquery.bootstrap.wizard.min.js') }}"></script>
  @include('gmapjs.base', ['lat' => $kota->first()->lat, 'lng' => $kota->first()->long])
  <script src="{{ asset('assets/js/order.js') }}"></script>
  @include('gmapjs.probe-marker', ['parameter' => '#sKota_Penerima', 'outLat' => '#sLat_Penerima', 'outLong' => '#sLong_Penerima'])
@endsection
@section('title')
Paket Baru
@endsection
@section('page')
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Rincian Paket</h3>
  </div>
  <form id="orderForm" role="form" method="post" action="@if(!Input::has('nama_pengirim')){{ route('admin.pengiriman.store') }}@else{{ route('admin.pengiriman.update', $pengiriman->token) }}@endif">
    {!! csrf_field() !!}
    @if(Input::has('nama_pengirim'))
    {!! method_field('PUT') !!}
    @endif
    <div class="box-body">
      <div id="rootwizard">
        <ul>
          <li><a href="#tab1" data-toggle="tab">Pengirim</a></li>
          <li><a href="#tab2" data-toggle="tab">Penerima</a></li>
          <li><a href="#tab3" data-toggle="tab">Barang</a></li>
          <li><a href="#tab4" data-toggle="tab">Peta</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane" id="tab1">
            <h4 class="form-title">Data Pengirim Paket</h4>
            <hr>
            @include('templates.validation-base', ['parameter' => 'nama_pengirim'])
            <div class="form-group">
              <label for="sNamaPengirim">Nama</label>
              <input type="text" name="nama_pengirim" id="sNamaPengirim" value="@include('templates.value-input-template', ['parameter' => 'nama_pengirim'])" class="form-control required">
            </div>
            @include('templates.validation-base', ['parameter' => 'alamat_pengirim'])
            <div class="form-group">
              <label for="sAlamatPengirim">Alamat</label>
              <input type="text" name="alamat_pengirim" id="sAlamatPengirim" value="@include('templates.value-input-template', ['parameter' => 'alamat_pengirim'])" class="form-control required">
            </div>
            @include('templates.validation-base', ['paramater' => 'telepon_pengirim'])
            <div class="form-group">
              <label for="sTeleponPengirim">Telepon</label>
              <input type="text" name="telepon_pengirim" id="sTeleponPengirim" value="@include('templates.value-input-template', ['parameter' => 'telepon_pengirim'])" class="form-control required">
            </div>
          </div>
          <div class="tab-pane" id="tab2">
            <h4 class="form-title">Data Penerima Paket</h4>
            <hr>
            @include('templates.validation-base', ['parameter' => 'nama_penerima'])
            <div class="form-group">
              <label for="sNamaPenerima">Nama</label>
              <input type="text" name="nama_penerima" id="sNamaPenerima" value="@include('templates.value-input-template', ['parameter' => 'nama_penerima'])" class="form-control required">
            </div>
            @include('templates.validation-base', ['parameter' => 'alamat_penerima'])
            <div class="form-group">
              <label for="sAlamatPenerima">Alamat</label>
              <input type="text" name="alamat_penerima" id="sAlamatPenerima" value="@include('templates.value-input-template', ['parameter' => 'alamat_penerima'])" class="form-control required">
            </div>
            @include('templates.validation-base', ['parameter' => 'kota_penerima'])
            <div class="form-group">
              <label for="sKota_Penerima">Kota</label>
              <select class="form-control required" name="kota_penerima" id="sKota_Penerima">
                @foreach($kota as $k)
                <option value="{{ $k->id }}" @include('templates.value-option-template', ['parameter' => 'kota_penerima', 'currId' => $k->id]) lat={{ $k->lat }} long={{ $k->long }}>{{ $k->nama }}</option>
                @endforeach
              </select>
            </div>
            @include('templates.validation-base', ['paramater' => 'telepon_penerima'])
            <div class="form-group">
              <label for="sTeleponPenerima">Telepon</label>
              <input type="text" name="telepon_penerima" id="sTeleponPenerima" value="@include('templates.value-input-template', ['parameter' => 'telepon_penerima'])" class="form-control required">
            </div>
            @include('templates.validation-base', ['paramater' => 'email_penerima'])
            <div class="form-group">
              <label for="sEmailPenerima">E-mail</label>
              <input type="text" name="email_penerima" id="sEmailPenerima" value="@include('templates.value-input-template', ['parameter' => 'email_penerima'])" class="form-control required">
            </div>
          </div>
          <div class="tab-pane" id="tab3">
            <h4 class="form-title">Data Barang</h4>
            <hr>
            @include('templates.validation-base', ['parameter' => 'volume_barang'])
            <div class="form-group">
              <label for="sVolumeBarang">Volume</label>
              <input type="text" name="volume_barang" id="sVolumeBarang" value="@include('templates.value-input-template', ['parameter' => 'volume_barang'])" class="form-control required">
            </div>
            @include('templates.validation-base', ['parameter' => 'berat_barang'])
            <div class="form-group">
              <label for="sBeratBarang">Berat</label>
              <input type="text" name="berat_barang" id="sBeratBarang" value="@include('templates.value-input-template', ['parameter' => 'berat_barang'])" class="form-control required">
            </div>
          </div>
          <div class="tab-pane" id="tab4">
            <div class="row">
              <div class="col-md-8">
                <div class="" id="map-canvas"></div>
              </div>
              <div class="col-md-4">
                @include('templates.validation-base', ['parameter' => 'lat_penerima'])
                <div class="form-group">
                  <label for="sLat_Penerima">Latitude</label>
                  <input type="text" name="lat_penerima" id="sLat_Penerima" value="@include('templates.value-input-template', ['parameter' => 'lat_penerima'])" class="form-control required" readonly="true">
                </div>
                @include('templates.validation-base', ['parameter' => 'long_penerima'])
                <div class="form-group">
                  <label for="sLong_Penerima">Longitude</label>
                  <input type="text" name="long_penerima" id="sLong_Penerima" value="@include('templates.value-input-template', ['parameter' => 'long_penerima'])" class="form-control required" readonly="true">
                </div>
              </div>
            </div>
          </div>
          <hr>
          <div class="pull-right">
            <a class="btn btn-default" id="btn-next" href="#">Lanjut</a>
            <input type="submit" value="Simpan" class="btn btn-primary" id="btn-finish" style="display: none;" type="button">
          </div>
        </div>
      </div>
    </div>
  </form>
</div>
@endsection

resources/views/backends/pengiriman-list.blade.php
@extends('templates.backend-base')
@section('css')
  @parent
@endsection
@section('js')
  @parent
  <script src="{{ asset('assets/js/popup.js') }}"></script>
@endsection
@section('title')
Daftar Paket
@endsection
@section('page')
<div class="col-xs-12">
  <div class="box box-primary">
    <div class="box-header">
      <h3 class="box-title">List</h3>
      <div class="box-tools">
        <div class="input-group input-group-sm" style="width: 150px;">
          <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">
          <div class="input-group-btn">
            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        @include('templates.alert-base')
      </div>
    </div>
    <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
        <tr>
          <th>Token</th>
          <th>Nama Pengirim</th>
          <th>Alamat Pengirim</th>
          <th>Nama Penerima</th>
          <th>Alamat Penerima</th>
          <th>Status</th>
          <th>Kota</th>
          <th></th>
          <th></th>
        </tr>
        @foreach($pengiriman as $p)
        <tr>
          <td><a href="#" onClick="PopupCenter('{{ route('admin.pengiriman.show', $p->token) }}', '123', '450', '620');">{{ str_limit($p->token, 10) }}</a></td>
          <td>{{ $p->nama_pengirim }}</td>
          <td>{{ str_limit($p->alamat_pengirim, 15) }}</td>
          <td>{{ $p->nama_penerima }}</td>
          <td>{{ str_limit($p->alamat_penerima, 15) }}</td>
          <td><span class="label {{ $p->status->labelclass }}">{{ $p->status->status }}</span></td>
          <td>{{ $p->kantor->kota->nama }}</td>
          <td class="align-center">
          @if(isset($editable) && $editable)
          <a href="{{ route('admin.pengiriman.edit', $p->token) }}"><button class="btn btn-warning"><i class="ion ion-edit"></i></button></a>
          @endif
          </td>
          <td class="align-center">
          @if(isset($deleteable) && $deleteable)
          <form method="post" action="{{ route('admin.pengiriman.destroy', $p->token) }}">{!! method_field('delete') !!}{!! csrf_field() !!}<button type="submit" class="btn btn-danger"><i class="ion ion-close-circled"></i></button></form>
          @endif
          </td>
        </tr>
        @endforeach
      </table>
    </div>
  </div>
  <div class="text-center">
    {!! $pengiriman->render() !!}
  </div>
</div>
@endsection

resources/views/backends/user-form.blade.php
@extends('templates.backend-base')
@section('css')
  @parent
  <link rel="stylesheet" href="assets/css/form.css">
@endsection
@section('js')
  @parent
  <script src="{{ asset('vendor/jquery-validation/dist/jquery.validate.min.js') }}"></script>
  <script src="{{ asset('vendor/twitter-bootstrap-wizard/jquery.bootstrap.wizard.min.js') }}"></script>
  <script src="{{ asset('assets/js/order.js') }}"></script>
@endsection
@section('title')
Tambah User / Edit User
@endsection
@section('page')
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Rincian User</h3>
  </div>
  <form id="orderForm" role="form" method="post" action="@if(!Input::has('name')){{ route('admin.user.store') }}@else{{ route('admin.user.update', $user->id) }}@endif">
    {!! csrf_field() !!}
    @if(Input::has('name'))
    {!! method_field('PUT') !!}
    @endif
    <div class="box-body">
      <div id="rootwizard">
        <ul>
          <li><a href="#tab1" data-toggle="tab">Rincian</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane" id="tab1">
            <h4 class="form-title">Data Dasar</h4>
            <hr>
            @include('templates.validation-base', ['parameter' => 'name'])
            <div class="form-group">
              <label for="sName">Nama</label>
              <input type="text" name="name" id="sName" value="@include('templates.value-input-template', ['parameter' => 'name'])" class="form-control required">
            </div>
            @include('templates.validation-base', ['parameter' => 'email'])
            <div class="form-group">
              <label for="sEmail">E-mail</label>
              <input type="email" name="email" id="sEmail" value="@include('templates.value-input-template', ['parameter' => 'email'])" class="form-control required">
            </div>
            @include('templates.validation-base', ['parameter' => 'password'])
            @if(Input::has('name'))
            <div class="form-group">
              <label for="sold_Password">Old Password</label>
              <input type="password" name="old_password" id="sold_Password" class="form-control">
            </div>
            @endif
            <div class="form-group">
              <label for="sPassword">Password</label>
              <input type="password" name="password" id="sPassword" class="form-control @if(!Input::has('name')){{ 'required' }}@endif">
            </div>
            <div class="form-group">
              <label for="sPasswordConfirmed">Konfirmasi Password</label>
              <input type="password" name="password_confirmation" value="" class="form-control @if(!Input::has('name')){{ 'required' }}@endif">
            </div>
            @include('templates.validation-base', ['parameter' => 'kantor_id'])
            <div class="form-group">
              <label for="sKantor">Kantor</label>
              <select class="form-control required" name="kantor_id" id="sKantor">
                @foreach($kantor as $k)
                <option value="{{ $k->id }}" @include('templates.value-option-template', ['parameter' => 'kantor_id', 'currId' => $k->id])>{{ $k->nama }} ({{ $k->kota->nama }})</option>
                @endforeach
              </select>
            </div>
          </div>
          <hr>
          <div class="pull-right">
            <input type="submit" value="Simpan" class="btn btn-primary" id="btn-finish" style="display: none;" type="button">
          </div>
        </div>
      </div>
    </div>
  </form>
</div>
@endsection