app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('login', [
  'as'   => 'login',
  'uses' => 'UserController@getLogin'
]);

Route::post('login', [
  'as'   => 'login',
  'uses' => 'UserController@postLogin'
]);

Route::get('logout', [
  'as'   => 'logout',
  'uses' => 'UserController@getLogout'
]);

Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function(){
    Route::group(['middleware' => 'plebs'], function(){
      Route::resource('pengiriman', 'PengirimanController');
    });

    Route::group(['middleware' => 'superuser'], function(){
      Route::resource('kantordistribusi', 'KantorDistribusiController');
      Route::resource('kota', 'KotaController');
      Route::resource('user', 'UserController', [
        'except' => ['show']
      ]);
    });

    //getIndex and getAllDaftarPengiriman can be done in more laravelistic using nested resource controller
    Route::controller('/', 'DashboardController', [
      'getIndex'               => 'admin.index',
      'getAllDaftarPengiriman' => 'admin.all-pengiriman',
      'getDaftarPengiriman'    => 'admin.status-pengiriman',
      'getPaketMasuk'          => 'admin.getpaketmasuk',
      'postPaketMasuk'         => 'admin.postpaketmasuk',
      'getPaketKeluar'         => 'admin.getpaketkeluar',
      'postPaketKeluar'        => 'admin.postpaketkeluar',
    ]);
});

Route::controller('/', 'FrontendController', [
  'getIndex'      => 'home',
  'getAboutUs'    => 'aboutus',
  'getKantor'     => 'kantor',
  'getTracking'   => 'tracking',
  'postTracking'  => 'tracking',
  'getKonfirmasi' => 'konfirmasi',
  'postKonfirmasi'=> 'konfirmasi',
]);

resources/views/templates/alert-base.blade.php
@if(session()->has('danger') || session()->has('warning') || session()->has('success'))
  <div class="alert
  @if(session()->has('danger'))
  {{ 'alert-danger' }}
  @elseif(session()->has('warning'))
  {{ 'alert-warning' }}
  @elseif(session()->has('success'))
  {{ 'alert-success' }}
  @endif
   alert-dismissible">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
    <b>@if(session()->has('danger'))
    {{ session()->pull('danger') }}
    @elseif(session()->has('warning'))
    {{ session()->pull('warning') }}
    @elseif(session()->has('success'))
    {{ session()->pull('success') }}
    @endif</b>
  </div>
@endif

resources/views/templates/backend-base.blade.php
@extends('templates.master-base')
@section('css')
  <link rel="stylesheet" href="{{ asset('vendor/AdminLTE/dist/css/AdminLTE.min.css') }}">
  <link rel="stylesheet" href="{{ asset('vendor/AdminLTE/dist/css/skins/skin-black.min.css') }}">
@endsection
@section('js')
  <script src="{{ asset('vendor/AdminLTE/dist/js/app.min.js') }}"></script>
@endsection
@section('body-class'){{ 'hold-transition skin-black sidebar-mini' }}@append
@section('body')
<div class="wrapper">
  @include('templates.backend-header')
  @include('templates.backend-sidebar')
  <div class="content-wrapper">
    <section class="content-header">
      <h1>
      @yield('title')
      <small>@yield('subtitle')</small>
      </h1>
    </section>
    <section class="content">
      <div class="row">
        @section('page')

        @show
      </div>
    </section>
  </div>
  @include('templates.backend-footer')
</div>
@endsection

resources/views/templates/backend-footer.blade.php
<footer class="main-footer">
  <strong>Copyright &copy; 2015 Ashadi Delivery Corp.</strong> All rights reserved.
</footer>

resources/views/templates/backend-header.blade.php
<header class="main-header">
  <a href="{{ route('admin.index') }}" class="logo">
    <span class="logo-mini"><b>A</b>DS</span>
    <span class="logo-lg"><b>Ashadi</b> <small>Delivery System</small></span>
  </a>
  <nav class="navbar navbar-static-top" role="navigation">
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown messages-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-envelope-o"></i>
            <span class="label label-success">4</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 4 messages</li>
            <li>
              <ul class="menu">
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="{{ asset('vendor/AdminLTE/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
                    </div>
                    <h4>
                      Support Team
                      <small><i class="fa fa-clock-o"></i> 5 mins</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
              </ul>
            </li>
            <li class="footer"><a href="#">See All Messages</a></li>
          </ul>
        </li>
        <li class="dropdown notifications-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-bell-o"></i>
            <span class="label label-warning">10</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 10 notifications</li>
            <li>
              <ul class="menu">
                <li>
                  <a href="#">
                    <i class="fa fa-users text-aqua"></i> 5 new members joined today
                  </a>
                </li>
              </ul>
            </li>
            <li class="footer"><a href="#">View all</a></li>
          </ul>
        </li>
        <li class="dropdown tasks-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-flag-o"></i>
            <span class="label label-danger">9</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 9 tasks</li>
            <li>
              <ul class="menu">
                <li>
                  <a href="#">
                    <h3>
                      Design some buttons
                      <small class="pull-right">20%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">20% Complete</span>
                      </div>
                    </div>
                  </a>
                </li>
              </ul>
            </li>
            <li class="footer">
              <a href="#">View all tasks</a>
            </li>
          </ul>
        </li>
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img src="{{ asset('vendor/AdminLTE/dist/img/user2-160x160.jpg') }}" class="user-image" alt="User Image">
            <span class="hidden-xs">Alexander Pierce</span>
          </a>
          <ul class="dropdown-menu">
            <li class="user-header">
              <img src="{{ asset('vendor/AdminLTE/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
              <p>
                Alexander Pierce - Web Developer
                <small>Member since Nov. 2012</small>
              </p>
            </li>
            <li class="user-footer">
              <div class="pull-right">
                <a href="{{ route('logout') }}" class="btn btn-default btn-flat">Sign out</a>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

resources/views/templates/backend-sidebar.blade.php
<aside class="main-sidebar">
  <section class="sidebar">
    <ul class="sidebar-menu">
      <li class="header">Menu</li>
      <li class="@if(Request::url() == route('admin.index')){{ 'active' }}@endif"><a href="{{ route('admin.index') }}"><i class="fa fa-envelope-o"></i> <span>Dashboard</span></a></li>
      {{-- Ordinary user --}}
      @if(Auth::user()->kantor()->first() != null)
      <li class="@if(Request::url() == route('admin.pengiriman.create')){{ 'active' }}@endif"><a href="{{ route('admin.pengiriman.create') }}"><i class="fa fa-pencil-square-o"></i> <span>Pengiriman Baru</span></a></li>
      <li class="@if((Request::url() == route('admin.pengiriman.index')) || Request::is('admin/pengiriman/*/edit')){{ 'active' }}@endif"><a href="{{ route('admin.pengiriman.index') }}"><i class="fa fa-cube"></i> <span>Pengiriman</span></a></li>
      <li class="treeview @if(Request::is('admin/paket*')){{ 'active' }}@endif">
        <a href="#"><i class="fa fa-send-o"></i><span>Mobilitas Paket</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
          <li><a href="{{ route('admin.getpaketmasuk') }}">Paket Masuk</a></li>
          <li><a href="{{ route('admin.getpaketkeluar') }}">Paket Keluar</a></li>
        </ul>
      </li>
      @endif
      <li class="treeview @if(Request::is('admin/*daftar-pengiriman*')){{ 'active' }}@endif">
        <a href="#"><i class="fa fa-cubes"></i> <span>Status Pengiriman</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
          <li><a href="{{ route('admin.all-pengiriman') }}">All</a></li>
          @foreach(\App\Models\StatusPengiriman::all() as $status_pengiriman)
          <li><a href="{{ route('admin.status-pengiriman', $status_pengiriman->id) }}">{{ $status_pengiriman->status }}</a></li>
          @endforeach
        </ul>
      </li>
      {{-- Super Admin only (those who had kantor_id = null) --}}
      @if(Auth::user()->kantor()->first() == null)
      <li class="treeview @if(Request::is('admin/user*')){{ 'active' }}@endif">
        <a href="#"><i class="fa fa-user"></i><span>Manajemen User</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
          <li><a href="{{ route('admin.user.index') }}">Daftar User</a></li>
          <li><a href="{{ route('admin.user.create') }}">Tambah User</a></li>
        </ul>
      </li>
      <li class="treeview @if(Request::is('admin/kantordistribusi*')){{ 'active' }}@endif">
        <a href="#"><i class="fa fa-building"></i><span>Manajemen Kantor</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
          <li><a href="{{ route('admin.kantordistribusi.index') }}">Daftar Kantor</a></li>
          <li><a href="{{ route('admin.kantordistribusi.create') }}">Tambah Kantor</a></li>
        </ul>
      </li>
      <li class="treeview @if(Request::is('admin/kota*')){{ 'active' }}@endif">
        <a href="#"><i class="fa fa-map-o"></i><span>Manajemen Kota</span><i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
          <li><a href="{{ route('admin.kota.index') }}">Daftar Kota</a></li>
          <li><a href="{{ route('admin.kota.create') }}">Tambah Kota</a></li>
        </ul>
      </li>
      @endif
    </ul>
  </section>
</aside>

resources/views/templates/email-base.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    @section('meta')

    @show
    <title>Ashadi Delivery System | @yield('title')</title>
  </head>
  <body>
    <div>
      Yth. bpk/ibu/sdr @yield('recipient')
    </div>
    <div>
      @section('page')

      @show
    </div>
    <div>
      Terima kasih atas perhatian bpk/ibu/sdr.
      Salam Hangat dari kami,
      Tim Ashadi Delivery System
    </div>
  </body>
</html>

resources/views/templates/frontend-base.blade.php
@extends('templates.master-base')
@section('css')
  <link rel="stylesheet" href="assets/css/frontend.css">
  
@endsection
@section('js')

@endsection
@section('body-class') @show
@section('body')
  @include('templates.frontend-header')
  <div class="container">
    <div class="row">
      <div class="col-md-12" style="min-height: 70vh;">
        <h3>@yield('title')</h3>
        <hr>
        <p>
          @yield('subtitle')
        </p>
        @section('page')

        @show
      </div>
    </div>
    @include('templates.frontend-footer')
  </div>
@endsection

resources/views/templates/frontend-footer.blade.php
<div class="row">
  <div class="text-center">
    <strong>Copyright &copy; 2015 Ashadi Delivery Corp.</strong> All rights reserved.<br/>
    <small><span class="label label-success">Delivering your <i class="ion ion-cube"></i></span> <i class="label label-warning">nowhere</i></small>
  </div>
</div>

resources/views/templates/frontend-header.blade.php
<header class="navbar navbar-static-top navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ route('home') }}"><b>Ashadi</b> Delivery System</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="@if(Request::url() == route('home')){{ 'active' }}@endif"><a href="{{ route('home') }}">Beranda</a></li>
        <li class="@if(Request::url() == route('kantor')){{ 'active' }}@endif"><a href="{{ route('kantor') }}">Kantor Cabang</a></li>
        <li class="@if(Request::url() == route('tracking')){{ 'active' }}@endif"><a href="{{ route('tracking') }}">Tracking</a></li>
        <li class="@if(Request::url() == route('aboutus')){{ 'active' }}@endif"><a href="{{ route('aboutus') }}">Tentang Kami</a></li>
      </ul>
    </div>
  </div>
</header>

resources/views/templates/master-base.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    @section('meta')

    @show
    <link rel="stylesheet" href="{{ asset('vendor/bootstrap/dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/font-awesome/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/Ionicons/css/ionicons.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/map-canvas.css')}}">
    @section('css')

    @show
    <title>Ashadi Delivery System Administration - @yield('title')</title>
  </head>
  <body class="@yield('body-class')">
    @section('body')

    @show
    <script src="{{ asset('vendor/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('vendor/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    @section('js')

    @show
  </body>
</html>

resources/views/templates/popup-base.blade.php
@extends('templates.master-base')
@section('css')
  <link rel="stylesheet" href="{{ asset('vendor/Ionicons/css/ionicons.min.css') }}">
  <link rel="stylesheet" href="{{ asset('vendor/AdminLTE/dist/css/AdminLTE.min.css') }}">
  <link rel="stylesheet" href="{{ asset('vendor/AdminLTE/dist/css/skins/skin-black.min.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/css/popup.css') }}">
@endsection
@section('js')
  <script src="{{ asset('vendor/AdminLTE/dist/js/app.min.js') }}"></script>
@endsection
@section('body-class'){{ 'skin-black' }}@append
@section('body')
<div class="wrapper">
  <div class="content-wrapper pop-up">
    <section class="content-header">
      <h1>
      @yield('title')
      <small>@yield('subtitle')</small>
      </h1>
    </section>
    <section class="content">
      @section('page')

      @show
    </section>
  </div>
</div>
@endsection

resources/views/templates/validation-base.blade.php
@if(isset($parameter) && ($errors->has($parameter)))
  <div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
    <b>{{ $errors->first($parameter) }}</b>
  </div>
@endif

resources/views/templates/value-input-template.blade.php
@if(isset($parameter))
@if(Input::has($parameter) && (Input::old($parameter) == "")){{ Input::get($parameter) }}
@else{{ Input::old($parameter) }}
@endif
@endif

resources/views/templates/value-option-template.blade.php
@if(isset($parameter) && isset($currId))
<?php
  $ref = Input::old($parameter);
  if(Input::has($parameter) && (Input::old($parameter) == ""))
  {
    $ref = Input::get($parameter);
  }
?>
@if($currId == $ref){{ 'selected' }}
@endif
@endif